CREATE TABLE IF NOT EXISTS cards_emblems
(
    card_id   BIGINT REFERENCES cards (id) ON DELETE CASCADE ON UPDATE CASCADE,
    emblem_id BIGINT REFERENCES emblems (id) ON DELETE CASCADE ON UPDATE CASCADE,

    PRIMARY KEY (card_id, emblem_id)
);
